In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import pandas as pd

In [2]:
twoD_list = [[11,12,13],[21,22,23],[31,32,33]]
twoD_tensor = torch.tensor(twoD_list)
twoD_tensor

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [3]:
twoD_tensor.ndimension()

2

In [4]:
twoD_tensor.shape


torch.Size([3, 3])

In [5]:
twoD_tensor.size()


torch.Size([3, 3])

In [6]:
twoD_tensor.numel()

9

In [7]:
twoD_numpy = twoD_tensor.numpy()
print("Tensor -> numpy....")
twoD_numpy
print("Type after converting: ", twoD_numpy.dtype)

Tensor -> numpy....
Type after converting:  int64


In [8]:
twoD_numpy


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]], dtype=int64)

In [9]:
p = torch.from_numpy(twoD_numpy())

TypeError: 'numpy.ndarray' object is not callable

In [10]:
p=  torch.from_numpy(twoD_numpy)
p

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [11]:
p.dtype

torch.int64

In [13]:
# Pandas Dataframe to a tensor
df = pd.DataFrame({'a':[11,21,31], 'b':[12,22,312]})
print("Pandas DataFrame to numpy: ",df.values)
print("Type Befroe converting: ",df.values.dtype)
print("=====================================================")

new_tensor = torch.from_numpy(df.values)
print("Pandas DataFrame to tensor: ",new_tensor)
print("Type AFTER converting: ",new_tensor.dtype)

Pandas DataFrame to numpy:  [[ 11  12]
 [ 21  22]
 [ 31 312]]
Type Befroe converting:  int64
Pandas DataFrame to tensor:  tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])
Type AFTER converting:  torch.int64


In [14]:
df


a    b
0  11   12
1  21   22
2  31  312

In [15]:
new_tensor

tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])

In [16]:
#converting Pandas Series to tensor
df = pd.DataFrame({'A':[11,33,22],'B':[3,3,2]})
new_t = torch.from_numpy(df.values)
new_t

tensor([[11,  3],
        [33,  3],
        [22,  2]])

In [17]:
t_ex = torch.tensor([[11,12,13],[21,22,23],[31,32,33]])
print("What is the value on 2nd_row 3rd_colum?",t_ex[1,2])

What is the value on 2nd_row 3rd_colum? tensor(23)


In [18]:
t_ex[0]

tensor([11, 12, 13])

In [19]:
t_ex[0][0]



tensor(11)

In [20]:
t_ex[0,0:2]

tensor([11, 12])

In [21]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
sliced_tensor_example = tensor_example[1:3]
print("1. Slicing step on tensor_example: ")
print("Result after tensor_example[1:3]: ", sliced_tensor_example)
print("Dimension after tensor_example[1:3]: ", sliced_tensor_example.ndimension())
print("================================================")
print("2. Pick an index on sliced_tensor_example: ")
print("Result after sliced_tensor_example[1]: ", sliced_tensor_example[1])
print("Dimension after sliced_tensor_example[1]: ", sliced_tensor_example[1].ndimension())
print("================================================")
print("3. Combine these step together:")
print("Result: ", tensor_example[1:3][1])
print("Dimension: ", tensor_example[1:3][1].ndimension())

1. Slicing step on tensor_example: 
Result after tensor_example[1:3]:  tensor([[21, 22, 23],
        [31, 32, 33]])
Dimension after tensor_example[1:3]:  2
2. Pick an index on sliced_tensor_example: 
Result after sliced_tensor_example[1]:  tensor([31, 32, 33])
Dimension after sliced_tensor_example[1]:  1
3. Combine these step together:
Result:  tensor([31, 32, 33])
Dimension:  1


In [22]:
tensor_ques = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
tensor_ques[1][1] = tensor_ques[2][1]
tensor_ques

tensor([[11, 12, 13],
        [21, 32, 23],
        [31, 32, 33]])

In [27]:
#Tensor_operations
X = torch.tensor([[1,0],[0,1]])
Y = torch.tensor([[2,1],[1,2]])
c=X+Y
c

tensor([[3, 1],
        [1, 3]])

In [28]:
Y = torch.tensor([[2,1],[1,2]])
two_Y = 2*Y
two_Y

tensor([[4, 2],
        [2, 4]])

In [29]:
#Matrix multiplication
#mm
A = torch.tensor([[1,2,3],[1,0,1]])
B = torch.tensor([[1,2],[2,3],[4,5]])
torch.mm(A,B)


tensor([[17, 23],
        [ 5,  7]])

In [30]:
torch.dot(A,B)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [31]:
#dot연산은 1D tensor연산에만 가능, 2D에서는 mm메소드 사용한다.


In [32]:
X = torch.tensor([[1,2,3,4],[2,3,4,5]])
print("X의 모양: ",X.shape)
Y  = torch.tensor([[1,2],[2,3],[3,4],[5,6]])
print("Y의 모양 : ",Y.shape)
print("X*Y(2D): ", torch.mm(X,Y))

X의 모양:  torch.Size([2, 4])
Y의 모양 :  torch.Size([4, 2])
X*Y(2D):  tensor([[34, 44],
        [45, 59]])


In [33]:
torch.mm(Y,X)

tensor([[ 5,  8, 11, 14],
        [ 8, 13, 18, 23],
        [11, 18, 25, 32],
        [17, 28, 39, 50]])